### ISSUE TITLE
Adjust this library to Arduino's Library Manager format (and upload to it)

### ISSUE THREAD

**Issue by q2dg** [adafruit/Adafruit_CompositeVideo#1]
Hello.
In Readme.md it is said this fantastic library is primarily focused on Circuit PlayGround board, but I think if it were available on Arduino's Library Manager it would be far more popular
Thanks

**Comment by ladyada** [comment]
hiya its very very beta and its a little flakey so we'll probably not upt it on the manager at this time :)

**Comment by ladyada** [comment]
that said, we do hvae a guide about it - check it out here!
https://learn.adafruit.com/circuit-playground-express-dac-hacks/
